name: main
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          lix download
          npm install
      - name: Run tests
        run: haxe test.hxml
